version: "3.9"  # optional since v1.27.0
services:
  emaillist:
    build:
      context: ../
      dockerfile: Docker/Dockerfile
    volumes:
      - ./volumes:/email/volumes
    ports:
      - "8080:8080"
    environment:
    - DATABASE_URL=volumes/crud.db
    - APP_NAME=APPNAME
    - PORT=8080
    - IPBIND=0.0.0.0

